// 全国のジュニア料金対応ゴルフ場データ
const golfCourses = [
  // 関東エリア
  {
    id: 1,
    name: "霞ヶ関カンツリー倶楽部",
    prefecture: "埼玉県",
    region: "関東",
    city: "川越市",
    address: "埼玉県川越市霞ヶ関1-1-1",
    juniorPrice: "3,000円",
    regularPrice: "15,000円",
    description: "関東を代表する名門ゴルフ場。広大なコースと美しい自然に囲まれた環境で、ジュニアゴルファーも安心してプレーできます。",
    facilities: ["レストラン", "プロショップ", "練習場", "駐車場"],
    courseType: "丘陵コース",
    holes: 18,
    par: 72,
    yardage: "6,500ヤード",
    phone: "049-222-0001",
    website: "https://example.com/kasumigaseki",
    rakutenLink: "https://golf.rakuten.co.jp/kasumigaseki",
    image: "https://via.placeholder.com/800x600?text=Kasumigaseki+CC",
    rating: 4.8,
    tags: ["名門", "丘陵", "ジュニア歓迎"]
  },
  {
    id: 2,
    name: "東京ゴルフ倶楽部",
    prefecture: "東京都",
    region: "関東",
    city: "調布市",
    address: "東京都調布市若葉町1-2-3",
    juniorPrice: "2,500円",
    regularPrice: "12,000円",
    description: "都心からアクセス良好なゴルフ場。ジュニア向けのレッスンプログラムも充実しており、初心者から上級者まで楽しめます。",
    facilities: ["レストラン", "プロショップ", "練習場", "駐車場", "ジュニアレッスン"],
    courseType: "公園コース",
    holes: 18,
    par: 70,
    yardage: "5,800ヤード",
    phone: "042-481-0001",
    website: "https://example.com/tokyo-golf",
    rakutenLink: "https://golf.rakuten.co.jp/tokyo-golf",
    image: "https://via.placeholder.com/800x600?text=Tokyo+GC",
    rating: 4.5,
    tags: ["都心アクセス", "ジュニアレッスン", "初心者向け"]
  },
  {
    id: 3,
    name: "千葉カントリークラブ",
    prefecture: "千葉県",
    region: "関東",
    city: "千葉市",
    address: "千葉県千葉市中央区千葉港1-3-5",
    juniorPrice: "2,000円",
    regularPrice: "10,000円",
    description: "海を臨む絶景のゴルフ場。ジュニア料金がリーズナブルで、家族連れに人気です。",
    facilities: ["レストラン", "プロショップ", "練習場", "駐車場", "温泉"],
    courseType: "リンクスコース",
    holes: 18,
    par: 72,
    yardage: "6,200ヤード",
    phone: "043-245-0001",
    website: "https://example.com/chiba-cc",
    rakutenLink: "https://golf.rakuten.co.jp/chiba-cc",
    image: "https://via.placeholder.com/800x600?text=Chiba+CC",
    rating: 4.3,
    tags: ["海の見える", "家族向け", "リーズナブル"]
  },
  {
    id: 4,
    name: "神奈川ゴルフ倶楽部",
    prefecture: "神奈川県",
    region: "関東",
    city: "横浜市",
    address: "神奈川県横浜市港北区新横浜1-4-6",
    juniorPrice: "3,500円",
    regularPrice: "18,000円",
    description: "歴史ある名門コース。ジュニアゴルファーの育成に力を入れており、定期的にジュニア大会も開催されています。",
    facilities: ["レストラン", "プロショップ", "練習場", "駐車場", "クラブハウス"],
    courseType: "丘陵コース",
    holes: 18,
    par: 72,
    yardage: "6,800ヤード",
    phone: "045-471-0001",
    website: "https://example.com/kanagawa-golf",
    rakutenLink: "https://golf.rakuten.co.jp/kanagawa-golf",
    image: "https://via.placeholder.com/800x600?text=Kanagawa+GC",
    rating: 4.7,
    tags: ["名門", "ジュニア大会", "育成"]
  },
  {
    id: 5,
    name: "茨城ゴルフクラブ",
    prefecture: "茨城県",
    region: "関東",
    city: "つくば市",
    address: "茨城県つくば市研究学園1-5-7",
    juniorPrice: "1,800円",
    regularPrice: "8,500円",
    description: "広々としたコースでのびのびとプレーできる。ジュニア料金が格安で、練習にも最適です。",
    facilities: ["レストラン", "プロショップ", "練習場", "駐車場"],
    courseType: "平原コース",
    holes: 18,
    par: 71,
    yardage: "6,000ヤード",
    phone: "029-851-0001",
    website: "https://example.com/ibaraki-golf",
    rakutenLink: "https://golf.rakuten.co.jp/ibaraki-golf",
    image: "https://via.placeholder.com/800x600?text=Ibaraki+GC",
    rating: 4.2,
    tags: ["格安", "練習向け", "広々"]
  },
  {
    id: 6,
    name: "栃木カントリークラブ",
    prefecture: "栃木県",
    region: "関東",
    city: "宇都宮市",
    address: "栃木県宇都宮市大通り1-6-8",
    juniorPrice: "2,200円",
    regularPrice: "11,000円",
    description: "自然豊かな環境でゴルフを楽しめる。ジュニア向けの特別プランも用意されています。",
    facilities: ["レストラン", "プロショップ", "練習場", "駐車場", "温泉"],
    courseType: "森林コース",
    holes: 18,
    par: 72,
    yardage: "6,300ヤード",
    phone: "028-621-0001",
    website: "https://example.com/tochigi-cc",
    rakutenLink: "https://golf.rakuten.co.jp/tochigi-cc",
    image: "https://via.placeholder.com/800x600?text=Tochigi+CC",
    rating: 4.4,
    tags: ["自然豊か", "特別プラン", "温泉"]
  },
  {
    id: 7,
    name: "群馬ゴルフリゾート",
    prefecture: "群馬県",
    region: "関東",
    city: "前橋市",
    address: "群馬県前橋市大手町1-7-9",
    juniorPrice: "2,800円",
    regularPrice: "13,500円",
    description: "リゾート感あふれるゴルフ場。ジュニアゴルファーも快適にプレーできる設備が整っています。",
    facilities: ["レストラン", "プロショップ", "練習場", "駐車場", "ホテル", "温泉"],
    courseType: "リゾートコース",
    holes: 27,
    par: 72,
    yardage: "6,600ヤード",
    phone: "027-221-0001",
    website: "https://example.com/gunma-resort",
    rakutenLink: "https://golf.rakuten.co.jp/gunma-resort",
    image: "https://via.placeholder.com/800x600?text=Gunma+Resort",
    rating: 4.6,
    tags: ["リゾート", "ホテル", "27ホール"]
  },
  {
    id: 8,
    name: "埼玉ゴルフパーク",
    prefecture: "埼玉県",
    region: "関東",
    city: "さいたま市",
    address: "埼玉県さいたま市中央区本町1-8-10",
    juniorPrice: "1,500円",
    regularPrice: "7,500円",
    description: "気軽にプレーできるパブリックコース。ジュニア料金が非常にリーズナブルで、練習にも最適です。",
    facilities: ["レストラン", "プロショップ", "練習場", "駐車場"],
    courseType: "パブリックコース",
    holes: 18,
    par: 70,
    yardage: "5,900ヤード",
    phone: "048-851-0001",
    website: "https://example.com/saitama-park",
    rakutenLink: "https://golf.rakuten.co.jp/saitama-park",
    image: "https://via.placeholder.com/800x600?text=Saitama+Park",
    rating: 4.1,
    tags: ["パブリック", "格安", "気軽"]
  },
  // 北海道・東北エリア
  {
    id: 9,
    name: "札幌ゴルフ倶楽部",
    prefecture: "北海道",
    region: "北海道",
    city: "札幌市",
    address: "北海道札幌市中央区南1条西1-1-1",
    juniorPrice: "2,500円",
    regularPrice: "12,000円",
    description: "北海道を代表するゴルフ場。広大なコースと爽やかな空気の中で、ジュニアゴルファーも快適にプレーできます。",
    facilities: ["レストラン", "プロショップ", "練習場", "駐車場", "温泉"],
    courseType: "丘陵コース",
    holes: 18,
    par: 72,
    yardage: "6,400ヤード",
    phone: "011-231-0001",
    website: "https://example.com/sapporo-golf",
    rakutenLink: "https://golf.rakuten.co.jp/sapporo-golf",
    image: "https://via.placeholder.com/800x600?text=Sapporo+GC",
    rating: 4.6,
    tags: ["北海道", "広大", "爽やか"]
  },
  {
    id: 10,
    name: "仙台カントリークラブ",
    prefecture: "宮城県",
    region: "東北",
    city: "仙台市",
    address: "宮城県仙台市青葉区中央1-1-1",
    juniorPrice: "2,200円",
    regularPrice: "11,000円",
    description: "東北を代表する名門コース。ジュニア向けのレッスンも充実しています。",
    facilities: ["レストラン", "プロショップ", "練習場", "駐車場"],
    courseType: "丘陵コース",
    holes: 18,
    par: 72,
    yardage: "6,300ヤード",
    phone: "022-261-0001",
    website: "https://example.com/sendai-cc",
    rakutenLink: "https://golf.rakuten.co.jp/sendai-cc",
    image: "https://via.placeholder.com/800x600?text=Sendai+CC",
    rating: 4.5,
    tags: ["名門", "東北", "レッスン"]
  },
  // 中部エリア
  {
    id: 11,
    name: "名古屋ゴルフクラブ",
    prefecture: "愛知県",
    region: "中部",
    city: "名古屋市",
    address: "愛知県名古屋市中区錦1-1-1",
    juniorPrice: "2,800円",
    regularPrice: "14,000円",
    description: "中部地方を代表するゴルフ場。ジュニアゴルファーの育成に力を入れています。",
    facilities: ["レストラン", "プロショップ", "練習場", "駐車場", "クラブハウス"],
    courseType: "丘陵コース",
    holes: 18,
    par: 72,
    yardage: "6,600ヤード",
    phone: "052-231-0001",
    website: "https://example.com/nagoya-golf",
    rakutenLink: "https://golf.rakuten.co.jp/nagoya-golf",
    image: "https://via.placeholder.com/800x600?text=Nagoya+GC",
    rating: 4.7,
    tags: ["中部", "育成", "名門"]
  },
  {
    id: 12,
    name: "静岡ゴルフリゾート",
    prefecture: "静岡県",
    region: "中部",
    city: "静岡市",
    address: "静岡県静岡市葵区追手町1-1-1",
    juniorPrice: "2,400円",
    regularPrice: "11,500円",
    description: "富士山を望む絶景のゴルフ場。ジュニア料金がリーズナブルで、家族連れに人気です。",
    facilities: ["レストラン", "プロショップ", "練習場", "駐車場", "温泉", "ホテル"],
    courseType: "リゾートコース",
    holes: 18,
    par: 72,
    yardage: "6,200ヤード",
    phone: "054-251-0001",
    website: "https://example.com/shizuoka-resort",
    rakutenLink: "https://golf.rakuten.co.jp/shizuoka-resort",
    image: "https://via.placeholder.com/800x600?text=Shizuoka+Resort",
    rating: 4.4,
    tags: ["富士山", "リゾート", "家族向け"]
  },
  // 関西エリア
  {
    id: 13,
    name: "大阪ゴルフ倶楽部",
    prefecture: "大阪府",
    region: "関西",
    city: "大阪市",
    address: "大阪府大阪市北区梅田1-1-1",
    juniorPrice: "2,600円",
    regularPrice: "13,000円",
    description: "関西を代表するゴルフ場。都心からアクセス良好で、ジュニア向けのレッスンも充実しています。",
    facilities: ["レストラン", "プロショップ", "練習場", "駐車場", "ジュニアレッスン"],
    courseType: "公園コース",
    holes: 18,
    par: 70,
    yardage: "5,900ヤード",
    phone: "06-631-0001",
    website: "https://example.com/osaka-golf",
    rakutenLink: "https://golf.rakuten.co.jp/osaka-golf",
    image: "https://via.placeholder.com/800x600?text=Osaka+GC",
    rating: 4.5,
    tags: ["関西", "都心アクセス", "レッスン"]
  },
  {
    id: 14,
    name: "京都カントリークラブ",
    prefecture: "京都府",
    region: "関西",
    city: "京都市",
    address: "京都府京都市中京区烏丸通御池上る1-1-1",
    juniorPrice: "3,000円",
    regularPrice: "15,000円",
    description: "歴史ある古都のゴルフ場。伝統とモダンが融合したコースで、ジュニアゴルファーも楽しめます。",
    facilities: ["レストラン", "プロショップ", "練習場", "駐車場", "クラブハウス"],
    courseType: "丘陵コース",
    holes: 18,
    par: 72,
    yardage: "6,500ヤード",
    phone: "075-231-0001",
    website: "https://example.com/kyoto-cc",
    rakutenLink: "https://golf.rakuten.co.jp/kyoto-cc",
    image: "https://via.placeholder.com/800x600?text=Kyoto+CC",
    rating: 4.6,
    tags: ["京都", "歴史", "名門"]
  },
  // 中国・四国エリア
  {
    id: 15,
    name: "広島ゴルフクラブ",
    prefecture: "広島県",
    region: "中国",
    city: "広島市",
    address: "広島県広島市中区基町1-1-1",
    juniorPrice: "2,300円",
    regularPrice: "10,500円",
    description: "中国地方を代表するゴルフ場。ジュニア料金がリーズナブルで、練習にも最適です。",
    facilities: ["レストラン", "プロショップ", "練習場", "駐車場"],
    courseType: "丘陵コース",
    holes: 18,
    par: 72,
    yardage: "6,100ヤード",
    phone: "082-241-0001",
    website: "https://example.com/hiroshima-golf",
    rakutenLink: "https://golf.rakuten.co.jp/hiroshima-golf",
    image: "https://via.placeholder.com/800x600?text=Hiroshima+GC",
    rating: 4.3,
    tags: ["中国", "リーズナブル", "練習向け"]
  },
  {
    id: 16,
    name: "高知ゴルフリゾート",
    prefecture: "高知県",
    region: "四国",
    city: "高知市",
    address: "高知県高知市本町1-1-1",
    juniorPrice: "2,000円",
    regularPrice: "9,500円",
    description: "四国を代表するゴルフ場。自然豊かな環境でのびのびとプレーできます。",
    facilities: ["レストラン", "プロショップ", "練習場", "駐車場", "温泉"],
    courseType: "森林コース",
    holes: 18,
    par: 71,
    yardage: "6,000ヤード",
    phone: "088-821-0001",
    website: "https://example.com/kochi-resort",
    rakutenLink: "https://golf.rakuten.co.jp/kochi-resort",
    image: "https://via.placeholder.com/800x600?text=Kochi+Resort",
    rating: 4.2,
    tags: ["四国", "自然豊か", "格安"]
  },
  // 九州エリア
  {
    id: 17,
    name: "福岡ゴルフ倶楽部",
    prefecture: "福岡県",
    region: "九州",
    city: "福岡市",
    address: "福岡県福岡市博多区博多駅前1-1-1",
    juniorPrice: "2,500円",
    regularPrice: "12,000円",
    description: "九州を代表するゴルフ場。都心からアクセス良好で、ジュニア向けのレッスンも充実しています。",
    facilities: ["レストラン", "プロショップ", "練習場", "駐車場", "ジュニアレッスン"],
    courseType: "丘陵コース",
    holes: 18,
    par: 72,
    yardage: "6,200ヤード",
    phone: "092-431-0001",
    website: "https://example.com/fukuoka-golf",
    rakutenLink: "https://golf.rakuten.co.jp/fukuoka-golf",
    image: "https://via.placeholder.com/800x600?text=Fukuoka+GC",
    rating: 4.5,
    tags: ["九州", "都心アクセス", "レッスン"]
  },
  {
    id: 18,
    name: "鹿児島カントリークラブ",
    prefecture: "鹿児島県",
    region: "九州",
    city: "鹿児島市",
    address: "鹿児島県鹿児島市中央町1-1-1",
    juniorPrice: "2,200円",
    regularPrice: "10,500円",
    description: "南国を代表するゴルフ場。温暖な気候と美しい自然に囲まれた環境で、ジュニアゴルファーも快適にプレーできます。",
    facilities: ["レストラン", "プロショップ", "練習場", "駐車場", "温泉"],
    courseType: "リゾートコース",
    holes: 18,
    par: 72,
    yardage: "6,100ヤード",
    phone: "099-226-0001",
    website: "https://example.com/kagoshima-cc",
    rakutenLink: "https://golf.rakuten.co.jp/kagoshima-cc",
    image: "https://via.placeholder.com/800x600?text=Kagoshima+CC",
    rating: 4.4,
    tags: ["南国", "リゾート", "温暖"]
  }
];

// 全国47都道府県リスト
const prefectures = [
  "すべて",
  "北海道",
  "青森県", "岩手県", "宮城県", "秋田県", "山形県", "福島県",
  "茨城県", "栃木県", "群馬県", "埼玉県", "千葉県", "東京都", "神奈川県",
  "新潟県", "富山県", "石川県", "福井県", "山梨県", "長野県", "岐阜県", "静岡県", "愛知県",
  "三重県", "滋賀県", "京都府", "大阪府", "兵庫県", "奈良県", "和歌山県",
  "鳥取県", "島根県", "岡山県", "広島県", "山口県",
  "徳島県", "香川県", "愛媛県", "高知県",
  "福岡県", "佐賀県", "長崎県", "熊本県", "大分県", "宮崎県", "鹿児島県", "沖縄県"
];

// 地域区分
const regions = [
  "すべて",
  "北海道",
  "東北",
  "関東",
  "中部",
  "関西",
  "中国",
  "四国",
  "九州"
];

// ソートオプション
const sortOptions = [
  { value: "name", label: "名前順" },
  { value: "price-low", label: "ジュニア料金：安い順" },
  { value: "price-high", label: "ジュニア料金：高い順" },
  { value: "rating", label: "評価順" },
  { value: "prefecture", label: "都道府県順" },
  { value: "region", label: "地域順" }
];
