// 関東のジュニア料金対応ゴルフ場データ
const golfCourses = [
  {
    id: 1,
    name: "霞ヶ関カンツリー倶楽部",
    prefecture: "埼玉県",
    city: "川越市",
    address: "埼玉県川越市霞ヶ関1-1-1",
    juniorPrice: "3,000円",
    regularPrice: "15,000円",
    description: "関東を代表する名門ゴルフ場。広大なコースと美しい自然に囲まれた環境で、ジュニアゴルファーも安心してプレーできます。",
    facilities: ["レストラン", "プロショップ", "練習場", "駐車場"],
    courseType: "丘陵コース",
    holes: 18,
    par: 72,
    yardage: "6,500ヤード",
    phone: "049-222-0001",
    website: "https://example.com/kasumigaseki",
    rakutenLink: "https://golf.rakuten.co.jp/kasumigaseki",
    image: "https://via.placeholder.com/800x600?text=Kasumigaseki+CC",
    rating: 4.8,
    tags: ["名門", "丘陵", "ジュニア歓迎"]
  },
  {
    id: 2,
    name: "東京ゴルフ倶楽部",
    prefecture: "東京都",
    city: "調布市",
    address: "東京都調布市若葉町1-2-3",
    juniorPrice: "2,500円",
    regularPrice: "12,000円",
    description: "都心からアクセス良好なゴルフ場。ジュニア向けのレッスンプログラムも充実しており、初心者から上級者まで楽しめます。",
    facilities: ["レストラン", "プロショップ", "練習場", "駐車場", "ジュニアレッスン"],
    courseType: "公園コース",
    holes: 18,
    par: 70,
    yardage: "5,800ヤード",
    phone: "042-481-0001",
    website: "https://example.com/tokyo-golf",
    rakutenLink: "https://golf.rakuten.co.jp/tokyo-golf",
    image: "https://via.placeholder.com/800x600?text=Tokyo+GC",
    rating: 4.5,
    tags: ["都心アクセス", "ジュニアレッスン", "初心者向け"]
  },
  {
    id: 3,
    name: "千葉カントリークラブ",
    prefecture: "千葉県",
    city: "千葉市",
    address: "千葉県千葉市中央区千葉港1-3-5",
    juniorPrice: "2,000円",
    regularPrice: "10,000円",
    description: "海を臨む絶景のゴルフ場。ジュニア料金がリーズナブルで、家族連れに人気です。",
    facilities: ["レストラン", "プロショップ", "練習場", "駐車場", "温泉"],
    courseType: "リンクスコース",
    holes: 18,
    par: 72,
    yardage: "6,200ヤード",
    phone: "043-245-0001",
    website: "https://example.com/chiba-cc",
    rakutenLink: "https://golf.rakuten.co.jp/chiba-cc",
    image: "https://via.placeholder.com/800x600?text=Chiba+CC",
    rating: 4.3,
    tags: ["海の見える", "家族向け", "リーズナブル"]
  },
  {
    id: 4,
    name: "神奈川ゴルフ倶楽部",
    prefecture: "神奈川県",
    city: "横浜市",
    address: "神奈川県横浜市港北区新横浜1-4-6",
    juniorPrice: "3,500円",
    regularPrice: "18,000円",
    description: "歴史ある名門コース。ジュニアゴルファーの育成に力を入れており、定期的にジュニア大会も開催されています。",
    facilities: ["レストラン", "プロショップ", "練習場", "駐車場", "クラブハウス"],
    courseType: "丘陵コース",
    holes: 18,
    par: 72,
    yardage: "6,800ヤード",
    phone: "045-471-0001",
    website: "https://example.com/kanagawa-golf",
    rakutenLink: "https://golf.rakuten.co.jp/kanagawa-golf",
    image: "https://via.placeholder.com/800x600?text=Kanagawa+GC",
    rating: 4.7,
    tags: ["名門", "ジュニア大会", "育成"]
  },
  {
    id: 5,
    name: "茨城ゴルフクラブ",
    prefecture: "茨城県",
    city: "つくば市",
    address: "茨城県つくば市研究学園1-5-7",
    juniorPrice: "1,800円",
    regularPrice: "8,500円",
    description: "広々としたコースでのびのびとプレーできる。ジュニア料金が格安で、練習にも最適です。",
    facilities: ["レストラン", "プロショップ", "練習場", "駐車場"],
    courseType: "平原コース",
    holes: 18,
    par: 71,
    yardage: "6,000ヤード",
    phone: "029-851-0001",
    website: "https://example.com/ibaraki-golf",
    rakutenLink: "https://golf.rakuten.co.jp/ibaraki-golf",
    image: "https://via.placeholder.com/800x600?text=Ibaraki+GC",
    rating: 4.2,
    tags: ["格安", "練習向け", "広々"]
  },
  {
    id: 6,
    name: "栃木カントリークラブ",
    prefecture: "栃木県",
    city: "宇都宮市",
    address: "栃木県宇都宮市大通り1-6-8",
    juniorPrice: "2,200円",
    regularPrice: "11,000円",
    description: "自然豊かな環境でゴルフを楽しめる。ジュニア向けの特別プランも用意されています。",
    facilities: ["レストラン", "プロショップ", "練習場", "駐車場", "温泉"],
    courseType: "森林コース",
    holes: 18,
    par: 72,
    yardage: "6,300ヤード",
    phone: "028-621-0001",
    website: "https://example.com/tochigi-cc",
    rakutenLink: "https://golf.rakuten.co.jp/tochigi-cc",
    image: "https://via.placeholder.com/800x600?text=Tochigi+CC",
    rating: 4.4,
    tags: ["自然豊か", "特別プラン", "温泉"]
  },
  {
    id: 7,
    name: "群馬ゴルフリゾート",
    prefecture: "群馬県",
    city: "前橋市",
    address: "群馬県前橋市大手町1-7-9",
    juniorPrice: "2,800円",
    regularPrice: "13,500円",
    description: "リゾート感あふれるゴルフ場。ジュニアゴルファーも快適にプレーできる設備が整っています。",
    facilities: ["レストラン", "プロショップ", "練習場", "駐車場", "ホテル", "温泉"],
    courseType: "リゾートコース",
    holes: 27,
    par: 72,
    yardage: "6,600ヤード",
    phone: "027-221-0001",
    website: "https://example.com/gunma-resort",
    rakutenLink: "https://golf.rakuten.co.jp/gunma-resort",
    image: "https://via.placeholder.com/800x600?text=Gunma+Resort",
    rating: 4.6,
    tags: ["リゾート", "ホテル", "27ホール"]
  },
  {
    id: 8,
    name: "埼玉ゴルフパーク",
    prefecture: "埼玉県",
    city: "さいたま市",
    address: "埼玉県さいたま市中央区本町1-8-10",
    juniorPrice: "1,500円",
    regularPrice: "7,500円",
    description: "気軽にプレーできるパブリックコース。ジュニア料金が非常にリーズナブルで、練習にも最適です。",
    facilities: ["レストラン", "プロショップ", "練習場", "駐車場"],
    courseType: "パブリックコース",
    holes: 18,
    par: 70,
    yardage: "5,900ヤード",
    phone: "048-851-0001",
    website: "https://example.com/saitama-park",
    rakutenLink: "https://golf.rakuten.co.jp/saitama-park",
    image: "https://via.placeholder.com/800x600?text=Saitama+Park",
    rating: 4.1,
    tags: ["パブリック", "格安", "気軽"]
  }
];

// 都道府県リスト
const prefectures = ["すべて", "東京都", "神奈川県", "埼玉県", "千葉県", "茨城県", "栃木県", "群馬県"];

// ソートオプション
const sortOptions = [
  { value: "name", label: "名前順" },
  { value: "price-low", label: "ジュニア料金：安い順" },
  { value: "price-high", label: "ジュニア料金：高い順" },
  { value: "rating", label: "評価順" },
  { value: "prefecture", label: "都道府県順" }
];

